//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.DataDictionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari Description.
        /// </summary>
        public static string AfDescription {
            get {
                return ResourceManager.GetString("AfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari Title.
        /// </summary>
        public static string AfTitle {
            get {
                return ResourceManager.GetString("AfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencies.
        /// </summary>
        public static string AgenciesListTitle {
            get {
                return ResourceManager.GetString("AgenciesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Phone.
        /// </summary>
        public static string AgentPhoneNumber {
            get {
                return ResourceManager.GetString("AgentPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline.
        /// </summary>
        public static string AirlineType {
            get {
                return ResourceManager.GetString("AirlineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string ArDescription {
            get {
                return ResourceManager.GetString("ArDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Title.
        /// </summary>
        public static string ArTitle {
            get {
                return ResourceManager.GetString("ArTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttractionPlaces List.
        /// </summary>
        public static string AttractionPlacesListPageTitle {
            get {
                return ResourceManager.GetString("AttractionPlacesListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attraction Type.
        /// </summary>
        public static string AttractionType {
            get {
                return ResourceManager.GetString("AttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string BusType {
            get {
                return ResourceManager.GetString("BusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Changes.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string CEOAgentType {
            get {
                return ResourceManager.GetString("CEOAgentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all notifications.
        /// </summary>
        public static string CheckAllNotifs {
            get {
                return ResourceManager.GetString("CheckAllNotifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CommentState {
            get {
                return ResourceManager.GetString("CommentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Body.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Section Users.
        /// </summary>
        public static string CountSectionUsers {
            get {
                return ResourceManager.GetString("CountSectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Record.
        /// </summary>
        public static string CreateNewRecord {
            get {
                return ResourceManager.GetString("CreateNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeAgentType {
            get {
                return ResourceManager.GetString("EmployeeAgentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string EnDescription {
            get {
                return ResourceManager.GetString("EnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnName {
            get {
                return ResourceManager.GetString("EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title.
        /// </summary>
        public static string EnTitle {
            get {
                return ResourceManager.GetString("EnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi Description.
        /// </summary>
        public static string FaDescription {
            get {
                return ResourceManager.GetString("FaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi Name.
        /// </summary>
        public static string FaName {
            get {
                return ResourceManager.GetString("FaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi Title.
        /// </summary>
        public static string FaTitle {
            get {
                return ResourceManager.GetString("FaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Message Type.
        /// </summary>
        public static string GroupNotificationType {
            get {
                return ResourceManager.GetString("GroupNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalPlace.
        /// </summary>
        public static string HistoricalPlaceAttractionType {
            get {
                return ResourceManager.GetString("HistoricalPlaceAttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string HotelAlbumItem {
            get {
                return ResourceManager.GetString("HotelAlbumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Persian Name.
        /// </summary>
        public static string HotelFaName {
            get {
                return ResourceManager.GetString("HotelFaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string HotelLogo {
            get {
                return ResourceManager.GetString("HotelLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Names(split with , character).
        /// </summary>
        public static string HotelOtherNames {
            get {
                return ResourceManager.GetString("HotelOtherNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Count.
        /// </summary>
        public static string HotelRoomCount {
            get {
                return ResourceManager.GetString("HotelRoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Stars.
        /// </summary>
        public static string HotelStars {
            get {
                return ResourceManager.GetString("HotelStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Alt Text.
        /// </summary>
        public static string ImageAlt {
            get {
                return ResourceManager.GetString("ImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Image.
        /// </summary>
        public static string MainImage {
            get {
                return ResourceManager.GetString("MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Receiver.
        /// </summary>
        public static string MessageReceiver {
            get {
                return ResourceManager.GetString("MessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message State.
        /// </summary>
        public static string MessageState {
            get {
                return ResourceManager.GetString("MessageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string MuseumAttractionType {
            get {
                return ResourceManager.GetString("MuseumAttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild.
        /// </summary>
        public static string NotificationFaildState {
            get {
                return ResourceManager.GetString("NotificationFaildState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string NotificationReadState {
            get {
                return ResourceManager.GetString("NotificationReadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Name.
        /// </summary>
        public static string NotificationReceiverName {
            get {
                return ResourceManager.GetString("NotificationReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Data.
        /// </summary>
        public static string NotificationSendData {
            get {
                return ResourceManager.GetString("NotificationSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Read.
        /// </summary>
        public static string NotificationSentState {
            get {
                return ResourceManager.GetString("NotificationSentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string NotificationSubject {
            get {
                return ResourceManager.GetString("NotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string NotificationWaitingState {
            get {
                return ResourceManager.GetString("NotificationWaitingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherAttractionType {
            get {
                return ResourceManager.GetString("OtherAttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Representative.
        /// </summary>
        public static string RepresentativeAgentType {
            get {
                return ResourceManager.GetString("RepresentativeAgentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string RestaurantAttractionType {
            get {
                return ResourceManager.GetString("RestaurantAttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleNotificationType {
            get {
                return ResourceManager.GetString("RoleNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string SectionNotificationType {
            get {
                return ResourceManager.GetString("SectionNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Center.
        /// </summary>
        public static string ShopAttractionType {
            get {
                return ResourceManager.GetString("ShopAttractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Service Title.
        /// </summary>
        public static string TourServiceTitle {
            get {
                return ResourceManager.GetString("TourServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TrainType {
            get {
                return ResourceManager.GetString("TrainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Companies List.
        /// </summary>
        public static string TransportationCompaniesListPageTitle {
            get {
                return ResourceManager.GetString("TransportationCompaniesListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Type.
        /// </summary>
        public static string TransportationType {
            get {
                return ResourceManager.GetString("TransportationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo File.
        /// </summary>
        public static string TransportCoLogoFile {
            get {
                return ResourceManager.GetString("TransportCoLogoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Changes.
        /// </summary>
        public static string UpdateChanges {
            get {
                return ResourceManager.GetString("UpdateChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User .
        /// </summary>
        public static string UserNotificationType {
            get {
                return ResourceManager.GetString("UserNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        public static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
