//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.UIElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UIElements.UIElements", typeof(UIElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new hotel.
        /// </summary>
        public static string AddNewHotel {
            get {
                return ResourceManager.GetString("AddNewHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new medical nenter.
        /// </summary>
        public static string AddNewMedicalCenter {
            get {
                return ResourceManager.GetString("AddNewMedicalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with ❤ by Taban Team.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Facilities.
        /// </summary>
        public static string HotelFacilities {
            get {
                return ResourceManager.GetString("HotelFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels List.
        /// </summary>
        public static string HotelsList {
            get {
                return ResourceManager.GetString("HotelsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedicalCenter.
        /// </summary>
        public static string MedicalCenter {
            get {
                return ResourceManager.GetString("MedicalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Center List.
        /// </summary>
        public static string MedicalCenterList {
            get {
                return ResourceManager.GetString("MedicalCenterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taban Medical Management.
        /// </summary>
        public static string TabanMedicalManagement {
            get {
                return ResourceManager.GetString("TabanMedicalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of registered hotels.
        /// </summary>
        public static string TheNumberOfRegisteredHotels {
            get {
                return ResourceManager.GetString("TheNumberOfRegisteredHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of registeres medical center.
        /// </summary>
        public static string TheNumberOfRegisteresMedicalCenter {
            get {
                return ResourceManager.GetString("TheNumberOfRegisteresMedicalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View hotels.
        /// </summary>
        public static string ViewHotels {
            get {
                return ResourceManager.GetString("ViewHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View medical center.
        /// </summary>
        public static string ViewMedicalCenter {
            get {
                return ResourceManager.GetString("ViewMedicalCenter", resourceCulture);
            }
        }
    }
}
