//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency not found!.
        /// </summary>
        public static string AgencyNotFound {
            get {
                return ResourceManager.GetString("AgencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose a Location On The Map.
        /// </summary>
        public static string ChooseLocationOnTheMap {
            get {
                return ResourceManager.GetString("ChooseLocationOnTheMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, an error occurred while receiving the informations.
        /// </summary>
        public static string CouldNotGetInformations {
            get {
                return ResourceManager.GetString("CouldNotGetInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove pic.
        /// </summary>
        public static string CouldNotRemovePic {
            get {
                return ResourceManager.GetString("CouldNotRemovePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldnt Save Photo .
        /// </summary>
        public static string CouldNotSavePic {
            get {
                return ResourceManager.GetString("CouldNotSavePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Record!.
        /// </summary>
        public static string DuplicatedRecord {
            get {
                return ResourceManager.GetString("DuplicatedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0}  just in english characters.
        /// </summary>
        public static string EnterJustEnglishCharacters {
            get {
                return ResourceManager.GetString("EnterJustEnglishCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred!.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file Format Is not Valid. Valid Formats Are {0}.
        /// </summary>
        public static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file size is higher than {0} Mb.
        /// </summary>
        public static string FileSizeLimit {
            get {
                return ResourceManager.GetString("FileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Not Found!.
        /// </summary>
        public static string HotelNotFound {
            get {
                return ResourceManager.GetString("HotelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input type is not valid.
        /// </summary>
        public static string InputTypeIsNotValid {
            get {
                return ResourceManager.GetString("InputTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid .
        /// </summary>
        public static string InvalidInputValue {
            get {
                return ResourceManager.GetString("InvalidInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded photo is not a valid image file.
        /// </summary>
        public static string IsNotAValidImageFile {
            get {
                return ResourceManager.GetString("IsNotAValidImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found!.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max length of {0} should be {1}!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical center not found!.
        /// </summary>
        public static string MedicalCenterNotFound {
            get {
                return ResourceManager.GetString("MedicalCenterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Validation Error.
        /// </summary>
        public static string ModelValidationError {
            get {
                return ResourceManager.GetString("ModelValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Registered hotel facility in the system.
        /// </summary>
        public static string NoRegisterdFacility {
            get {
                return ResourceManager.GetString("NoRegisterdFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic received from you has been identified as dangerous. Please try again.
        /// </summary>
        public static string RecaptchaFailed {
            get {
                return ResourceManager.GetString("RecaptchaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Auth required!.
        /// </summary>
        public static string RequiredTwoFactor {
            get {
                return ResourceManager.GetString("RequiredTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted parameters are incorrect.
        /// </summary>
        public static string SubmittedParametersAreIncorrect {
            get {
                return ResourceManager.GetString("SubmittedParametersAreIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to display.
        /// </summary>
        public static string ThereIsNothingToDisplay {
            get {
                return ResourceManager.GetString("ThereIsNothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication is disabled. To continue, you must first enable this item.
        /// </summary>
        public static string TwoFactorAuthDisabled {
            get {
                return ResourceManager.GetString("TwoFactorAuthDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are limited for a while, please try again in a few minutes.
        /// </summary>
        public static string YouLockedOut {
            get {
                return ResourceManager.GetString("YouLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access or the resource is restricted!.
        /// </summary>
        public static string YouNotAllowed {
            get {
                return ResourceManager.GetString("YouNotAllowed", resourceCulture);
            }
        }
    }
}
